name: CI/CD Pipeline

on:
  push:
    branches:
      - dev/jose
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: ${{ secrets.SVC_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}
